# Generated by Django 5.2.3 on 2026-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('nombre_establecimiento', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('proyecto', models.CharField(max_length=100)),
                ('prioridad', models.IntegerField(default=0)),
                ('estado', models.CharField(default='Nuevo', max_length=50)),
                ('tiene_web', models.BooleanField(default=False)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead de Prospección',
                'verbose_name_plural': 'Leads de Prospección',
                'db_table': 'leads',
                'managed': True,
            },
        ),
    ]
