# Generated by Django 5.2.3 on 2026-04-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_timestamp', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.IntegerField(default=0)),
                ('is_group', models.BooleanField(default=False)),
                ('is_new_chat', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat WhatsApp',
                'verbose_name_plural': 'Chats WhatsApp',
                'db_table': 'chat_whatsapp',
                'ordering': ['-last_message_timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LeadConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajes', models.JSONField(default=list)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_seguimiento', 'En seguimiento'), ('no_respondio', 'No respondió'), ('convertido', 'Convertido')], default='nuevo', max_length=30)),
                ('followup_enviado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='leads_admin.lead')),
            ],
            options={
                'verbose_name': 'Conversación de Lead',
                'verbose_name_plural': 'Conversaciones de Leads',
                'db_table': 'lead_conversacion',
            },
        ),
        migrations.CreateModel(
            name='MensajeWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(max_length=100, unique=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.CharField(blank=True, max_length=20, null=True)),
                ('from_me', models.BooleanField(default=False)),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads_admin.chatwhatsapp')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'db_table': 'mensaje_whatsapp',
                'managed': True,
            },
        ),
    ]
