# Generated by Django 5.2.3 on 2026-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_admin', '0002_add_lead_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadconversacion',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_seguimiento', 'En seguimiento'), ('followup_24h', 'Follow‑up 24h'), ('followup_48h', 'Follow‑up 48h'), ('no_respondio', 'No respondió'), ('convertido', 'Convertido')], default='nuevo', max_length=30),
        ),
    ]
