# Generated by Django 5.2.3 on 2026-06-08 22:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0013_add_billing_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('gratuito', 'Capa Gratuita'), ('pro', 'Plan Pro')], default='gratuito', max_length=20)),
                ('amount_cop', models.IntegerField(default=0)),
                ('numero_barberos', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('trial', 'Trial 30 días'), ('expiring_soon', 'Por vencer'), ('expired', 'Vencida — Capa Gratuita'), ('suspended', 'Suspendida')], default='trial', max_length=20)),
                ('bold_payment_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_subscription', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Suscripción SaaS',
                'verbose_name_plural': 'Suscripciones SaaS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cop', models.IntegerField()),
                ('paid_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.saassubscription')),
            ],
            options={
                'verbose_name': 'Pago registrado',
                'verbose_name_plural': 'Pagos registrados',
                'ordering': ['-paid_at'],
            },
        ),
    ]
