# Generated by Django 5.2.3 on 2026-06-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_add_billing_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saassubscription",
            name="numero_barberos",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Calculado automáticamente según profesionales activos",
            ),
        ),
        migrations.AlterField(
            model_name="saassubscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("gratuito", "Capa Gratuita"),
                    ("pro", "Plan Pro"),
                    ("empresarial", "Plan Empresarial"),
                ],
                default="gratuito",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="saassubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Activa"),
                    ("trial", "Trial 30 días"),
                    ("trial_7d", "Trial 7 días (Bot)"),
                    ("expiring_soon", "Por vencer"),
                    ("expired", "Vencida — Capa Gratuita"),
                    ("suspended", "Suspendida"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
    ]
