# Generated by Django 5.2.3 on 2026-06-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_sistema_financiero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicionegocio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=25000, max_digits=8, null=True),
        ),
    ]
