# Generated by Django 5.2.3 on 2026-06-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0012_add_default_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='feature_asistente',
            field=models.BooleanField(default=False, verbose_name='Asistente de Agenda'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_backup',
            field=models.BooleanField(default=False, verbose_name='Backup diario'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_blacklist',
            field=models.BooleanField(default=False, verbose_name='Lista Negra'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_comisiones',
            field=models.BooleanField(default=False, verbose_name='Comisiones automáticas'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_estadisticas',
            field=models.BooleanField(default=False, verbose_name='Estadísticas avanzadas'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_marketing',
            field=models.BooleanField(default=False, verbose_name='Campañas SMS/Email'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_soporte_vip',
            field=models.BooleanField(default=False, verbose_name='Soporte VIP'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='feature_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Recordatorios WhatsApp'),
        ),
    ]
