# Generated by Django 5.2.3 on 2026-06-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_rename_clientes_blo_cliente_2c6d2f_idx_clientes_bl_cliente_533d74_idx_and_more'),
        ('negocios', '0013_add_billing_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono al que se envió', max_length=20)),
                ('tipo', models.CharField(choices=[('no_show', 'No-show (inasistencia)'), ('inactivo', 'Inactivo (toca peluquearse)')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_ok', models.BooleanField(default=False, help_text='El envío por WhatsApp fue exitoso')),
                ('respondio', models.BooleanField(default=False, help_text='El cliente respondió al mensaje')),
                ('reagendo', models.BooleanField(default=False, help_text='El cliente volvió a reservar tras el mensaje')),
                ('opt_out', models.BooleanField(default=False, help_text='El cliente pidió no recibir más mensajes')),
                ('detalle', models.TextField(blank=True, help_text='Notas/errores del envío')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to=settings.AUTH_USER_MODEL)),
                ('cliente_provisional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='clientes.clienteprovisional')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='negocios.negocio')),
                ('reserva_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones', to='clientes.reserva')),
            ],
            options={
                'verbose_name': 'Recuperación de Cliente (Win-Back)',
                'verbose_name_plural': 'Recuperaciones de Clientes (Win-Back)',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['negocio', 'tipo', 'fecha_envio'], name='clientes_re_negocio_e39185_idx'), models.Index(fields=['telefono', 'fecha_envio'], name='clientes_re_telefon_8170fd_idx'), models.Index(fields=['cliente', 'tipo'], name='clientes_re_cliente_aceaf1_idx'), models.Index(fields=['cliente_provisional', 'tipo'], name='clientes_re_cliente_a2d86a_idx')],
            },
        ),
    ]
