# Generated by Django 5.2.3 on 2026-06-08 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0006_salario_mensual_matriculacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profesionales/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales/portadas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
